### ISSUE TITLE
mintLocale doesnt allow me to set numeric format

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintlocale#20]
I live in the United Arab Emirates and after installing Linux Mint 17.1 the Languages dialog in Control Panel put my region as ar_AE.UTF8. This is all fine except that it shows numbers in arabic which i dont want to see as i'm a canadian and the dialog doesnt give me an option to fix this.

I ended up having to edit /etc/default/locale and setting LC_NUMERIC as "en_US.UTF-8" to solve this problem. It would be nice if there were a means of solving this problem within the GUI app.

**Comment by xenopeek** [comment]
We're bug squashing right now to improve on issue handling. As part of that we're going through old open issues. I doubt this issue is still a concern for you or that after this time you can recall further details so I'm closing. I'll reopen it if you respond with more information.

Basically we'd want more details as to why setting Region to something other than UAE was not an option for you. As in, was there a program that when you changed the Region in mintlocale to something other than UAE that — while now showing the numeric format as you want — as a consequence was showing other information not as you wanted? It would help to have a clear test case like that to consider this further.

Testing your issue on Linux Mint 18.3 and then retesting on Linux Mint 17.1, it seems nothing has been changed in the way mintlocale works with regard to your issue:

- Setting Language basically affects display language, sorting rules and time format (LANG, LANGUAGE, LC_CTYPE, LC_TIME, LC_COLLATE and LC_MESSAGES from /etc/default/locale).
- Setting Region basically affects numeric format and related things (LC_NUMERIC, LC_MONETARY, LC_PAPER, LC_NAME, LC_ADDRESS, LC_TELEPHONE, LC_MEASUREMENT and LC_IDENTIFICATION from /etc/default/locale). I don't know if all of those locale settings are actually used by many programs, aside from numeric format.
