### ISSUE TITLE
Allow for more fine-grained control of regional settings

### ISSUE THREAD

**Issue by cmeeren** [linuxmint/mintlocale#36]
Using Mint 17.3 with Cinnamon. The Language Settings offers options for "Language" and "Region". "Language" controls both the interface language as well as date/time. I want to have the interface language set to English but use Norwegian format for date and time. (I know I can use a custom date format for the clock, but this doesn't fix the display of other dates/times on the system, such as file modification times in Nemo).

In general I would like more fine-grained control of regional settings. For example, while I'd like most number formats set to Norwegian, I consistently use dot `.` as a decimal instead of the default Norwegian comma `,`. (I don't know yet if this is a problem in Linux/Mint, I have recently migrated from Windows and haven't dabbled with spreadsheets etc. yet.)

**Comment by clefebvre** [comment]
Hi @cmeeren, @vasanth3045 , @dqgls , we can look into this for 19.2.

Which variables in particular do you export and you'd like to be able to set?

**Comment by cmeeren** [comment]
I've long since returned to Windows, so I don't really care anymore. Unsubscribing, cc me if there's anything in particular.

**Comment by Saucistophe** [comment]
I ended here because of the initial conversation [here](https://forums.linuxmint.com/viewtopic.php?t=215738), because I had the very same concern that @cmeeren, so I'll take it from here! :smile:

The problem is that I'm used to having an OS in English (Because looking for settings is simpler, some names are changed, some are not, some are translated in an awkward way...).
But I'm also used to a specific _date format_. I'm used to weeks starting on Monday, and the day of the month being first; when I look for a date, I want to see at a glance if it's the 31st or the 3rd, not what month. I'm just wired this way because, hey, that's my locale.

So the idea would be to split the "Language" button, which controls both language and date format, to two or more buttons; one for language, one for date format. If that's possible and makes sense.

Thank you!

**Comment by erikhakansson** [comment]
I just want to add my support to this issue.

I use English language in Mint, but want Swedish date/time format. Date/time should be part of Region, not Language, alternatively, split up the different LC_* settings to allow setting them all individually.

**Comment by jdpiguet** [comment]
Same need for myself: Switzerland is having 3 official languages but all are using same region.
So I'd like to have the user interface in English, but the date/time format in Switzerland and the weekdays/monthes in the local language (french/german/italian).
I strongly suspect that Belgian people will have the same problem...

**Comment by exploide** [comment]
> Which variables in particular do you export and you'd like to be able to set?

I'm especially interested in `LC_TIME`.

**Comment by jdpiguet** [comment]
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_CH.UTF-8
LC_TIME=fr_CH.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_CH.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_CH.UTF-8
LC_NAME=fr_CH.UTF-8
LC_ADDRESS=fr_CH.UTF-8
LC_TELEPHONE=fr_CH.UTF-8
LC_MEASUREMENT=fr_CH.UTF-8
LC_IDENTIFICATION=fr_CH.UTF-8
LC_ALL=

Depending of the work I'm doing, I change fr_CH_UTF-8 to de_CH.UTF-8...

**Comment by clefebvre** [comment]
Implemented by https://github.com/linuxmint/mintlocale/commit/6ca3b7c8a6c246cc7af6cc5cb2095485274ef637
