### ISSUE TITLE
LMDE 3 only: Fcitx does not work (Qimpanel not visible)

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/mintlocale#61]
Title says it all. In LMDE 3 Qimpanel does not show up after activating Fcitx and typing, therefore making Fcitx unusable. Qimpanel is also invisible in fcitx-qimpanel-configtool. It does work in LM 19.
I would like to add that Fcitx works without any issues in Debian 9 (manual activation), with a Qimpanel different from Ubuntu/LM19. This is not a Debian bug.

**Comment by clefebvre** [comment]
Fcitx provides its own systray applet (which size is too small in Cinnamon but that's another issue). If fcitx-ui-qimpanel is installed, it overrides this applet and places itself there instead.

There seems to be a dependency issue with fcitx-ui-qimpanel in Debian though. As you said, it doesn't manage to load the input panel when typing Asian characters (I tested that with Hiragana/Mozc). If you remove fcitx-ui-qimpanel, fcitx then falls back to its own UI and this solves (well, works around the problem).

To make fcitx-ui-qimpanel work in LMDE3, install qml-module-qtquick-dialogs and qml-module-qtquick-controls. These should be added by Debian as dependencies for this package.

On our side we'll add these packages to the list of packages that mintlocale installs when you add support for Fcitx.

**Comment by clefebvre** [comment]
By the way, I see another issue here with fcitx-qimpanel... the applet menu doesn't show up.

**Comment by clefebvre** [comment]
OK, a little more info on this.

- The issue with fcitx's systray is specific to HiDPI. We might be able to fix that in Cinnamon.
- fcitx-ui-classic works quite well compared to fcitx-ui-qimpanel. In fact I find it simpler to use (input methods and keyboards are in their own submenus), more professional looking (items in ui-qimpanel such as "ConfigureFcitx" really don't look good) and it's not branded with tacky Ubuntu logos.
- I wasn't able to find the cause of the issue with fcitx-qimpanel not showing a systray menu.
- fcitx-qimpanel doesn't integrate well with the fcitx configuration screen. It provides its own tool and menu entry instead.

So with this in mind, it seems preferable to simply stick to Fcitx's own UI rather than install something that doesn't work as well. I'll remove fcitx-ui-qimpanel from the list of packages.

**Comment by harlekin777** [comment]
The issue with the two missing dependencies of qimpanel in Debian (which is in fact a Debian bug) does not appear to the user who sticks to the default, because by default Debian only installs fcitx-ui-classic together with fcitx, not fcitx-ui-qimpanel.

I agree 100% that classic looks and integrates much better than qimpanel. So dropping qimpanel is surely the best decision.

Thank you very much for your help. Also I would like to say a big thank you to you and to the entire Linux Mint team for making such an awesome, gorgeous desktop environment. Together with your user-friendly tools and the powerful Debian base your distro is the most polished system one can see around. I am amazed by it every day. Thanks again!

**Comment by clefebvre** [comment]
thanks @harlekin777  :)
